# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import multimodal_pb2 as multimodal__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in multimodal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultimodalServiceStub(object):
    """============================================================
    Service Definition
    - Unary and bidi-streaming entrypoints for clients.
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUnary = channel.unary_unary(
                '/multimodal.MultimodalService/SendUnary',
                request_serializer=multimodal__pb2.DataPacket.SerializeToString,
                response_deserializer=multimodal__pb2.Ack.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/multimodal.MultimodalService/Chat',
                request_serializer=multimodal__pb2.DataPacket.SerializeToString,
                response_deserializer=multimodal__pb2.Ack.FromString,
                _registered_method=True)


class MultimodalServiceServicer(object):
    """============================================================
    Service Definition
    - Unary and bidi-streaming entrypoints for clients.
    ============================================================

    """

    def SendUnary(self, request, context):
        """Simple unary request/response.

        Use when you have a single DataPacket and expect a single Ack,
        e.g., non-streaming use-cases or simple RPC-style operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Bidirectional streaming interface.

        Use for:
        - Video or camera streams (many DataPackets per logical session).
        - Chunked video or audio transport.
        - Any scenario with incremental results or long-lived sessions.

        Each inbound DataPacket should be matched by one or more Ack messages.
        The exact mapping (1:1 vs 1:N) is implementation-specific, but in the
        thin-proxy pattern we generally do 1:1: one Ack per DataPacket.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultimodalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUnary,
                    request_deserializer=multimodal__pb2.DataPacket.FromString,
                    response_serializer=multimodal__pb2.Ack.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=multimodal__pb2.DataPacket.FromString,
                    response_serializer=multimodal__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multimodal.MultimodalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multimodal.MultimodalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultimodalService(object):
    """============================================================
    Service Definition
    - Unary and bidi-streaming entrypoints for clients.
    ============================================================

    """

    @staticmethod
    def SendUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal.MultimodalService/SendUnary',
            multimodal__pb2.DataPacket.SerializeToString,
            multimodal__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multimodal.MultimodalService/Chat',
            multimodal__pb2.DataPacket.SerializeToString,
            multimodal__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
