channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - numpy==1.24.4
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.1.2
  - scipy==1.11.4
name: mlflow-env
