apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.env.name }}-state-pvc
  namespace: {{ .Values.env.namespace }}
  labels:
    app: {{ .Values.env.name }}-state
    type: {{ .Values.env.type }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dominodisk
  resources:
    requests:
      storage: {{ .Values.state.persistence.size | default "1Gi" }}
