apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-webhook-certificate"
spec:
  secretName: "{{ .Values.env.name }}-webhook-certs"
  dnsNames:
  - "{{ .Values.env.service }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.platform }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.platform }}.svc"
  issuerRef:
    name: "selfsigned-{{ .Values.env.name }}-webhook"
  duration: {{ .Values.certmanager.duration }}
  renewBefore: {{ .Values.certmanager.renewBefore }}
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}-webhook"
spec:
  selfSigned: {}