apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mutations.apps.dominodatalab.com
spec:
  group: apps.dominodatalab.com
  names:
    kind: Mutation
    listKind: MutationList
    plural: mutations
    singular: mutation
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - rules
          properties:
            rules:
              type: array
              items:
                type: object
                properties:
                  labelSelectors:
                    type: array
                    items:
                      type: string
                  hardwareTierIdSelector:
                    type: array
                    items:
                      type: string
                  notHardwareTierIdSelector:
                    type: array
                    items:
                      type: string
                  namespaceSelector:
                    type: array
                    items:
                      type: string
                  notNamespaceSelector:
                    type: array
                    items:
                      type: string
                  organizationSelector:
                    type: array
                    items:
                      type: string
                  notOrganizationSelector:
                    type: array
                    items:
                      type: string
                  usernameSelector:
                    type: array
                    items:
                      type: string
                  notUsernameSelector:
                    type: array
                    items:
                      type: string
                  projectSelector:
                    type: array
                    items:
                      type: string
                  notProjectSelector:
                    type: array
                    items:
                      type: string
                  sharedMemory:
                    type: object
                    properties:
                      limit:
                        type: string
                  matchBuilds:
                    type: boolean
                    default: false
                  userEvents:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      customMessage:
                        type: string
                  istioProbeRewrite:
                    type: object
                    properties: {}
                  istioPortException:
                    type: object
                    properties:
                      spark:
                        type: boolean
                        default: false
                      inbound:
                        type: array
                        items:
                          type: integer
                      outbound:
                        type: array
                        items:
                          type: integer
                  autoscaling:
                    type: object
                    properties:
                      CpuTargetPercentage:
                        type: integer
                      replicasMax:
                        type: integer
                    required:
                      - replicasMax
                      - CpuTargetPercentage
                  containerImageRewrite:
                    type: object
                    properties:
                      name:
                        type: string
                      originalImage:
                        type: string
                      newImage:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                      args:
                        type: array
                        items:
                          type: string
                    required:
                      - newImage
                  addToleration:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      value:
                        type: string
                      effect:
                        type: string
                    required:
                      - operator
                  modifyStorageClass:
                    type: object
                    properties:
                      storageClassName:
                        type: string
                    required:
                      - storageClassName
                  gpuToleration:
                    type: object
                    properties:
                      request:
                        type: integer
                    required:
                      - request
                  modifyAnnotation:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                      - key
                  modifyLabel:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                      - key
                  insertContainer:
                    type: object
                    properties:
                      containerType:
                        type: string
                        enum: [init, app]
                      spec:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                      - containerType
                      - spec
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        additionalProperties: true
                      requests:
                        type: object
                        additionalProperties: true
                  efa:
                    type: object
                    properties:
                      hugepage:
                        type: string
                        default: "256Mi"
                      numAdapters:
                        type: integer
                    required:
                      - hugepage
                      - numAdapters
                  insertVolumes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                      x-kubernetes-preserve-unknown-fields: true
                  insertExecutionJWT:
                    type: object
                    properties: {}
                  disableToolingProbe:
                    type: object
                    properties: {}
                  fuse:
                    type: object
                    properties: {}
                  serviceAccount:
                    type: object
                    properties: {}
                  insertVolumeMounts:
                    type: object
                    properties:
                      containerSelector:
                        type: array
                        items:
                          type: string
                      volumeMounts:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            mountPath:
                              type: string
                            subPath:
                              type: string
                          required:
                            - name
                            - mountPath
                          x-kubernetes-preserve-unknown-fields: true
                    required:
                      - volumeMounts
                  pvc:
                    type: object
                    properties:
                      claimName:
                        type: string
                      path:
                        type: string
                    required:
                      - claimName
                      - path
                  modifyEnv:
                    type: object
                    properties:
                      containerSelector:
                        type: array
                        items:
                          type: string
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                            valueFrom:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                          required:
                            - name
                  enforceCpuLicenseLimit:
                    type: object
                    properties:
                      image_for_license_enforcement:
                        type: string
                      replacement_image:
                        type: string
                        default: "busybox"
                      cpu_limit:
                        type: number
                      command:
                        type: array
                        items:
                          type: string
                        default: ["/bin/sh", "-c"]
                      args:
                        type: array
                        items:
                          type: string
                        default:
                          [
                            "echo failing because license exceeded for the image; exit 1;",
                          ]
                    required:
                      - image_for_license_enforcement
                      - replacement_image
                      - cpu_limit
                      - command
                      - args
                  modifyHWTier:
                    type: object
                    properties:
                      hwtier_id:
                        type: string
                    required:
                      - hwtier_id
                  labelModelOwner:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    required:
                      - key
                      - value
                  addClassName:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                    - name                        
                  modifySecurityContext:
                    type: object
                    properties:
                      containerSelector:
                        type: array
                        items:
                          type: string
                      kind:
                        type: string
                        enum: ["Pod", "Job","Deployment"]
                      context:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                      - context
                  insertModelAffinity:
                    type: object
                    properties:
                      affinity:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      topologySpreadConstraints:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  insertAffinity:
                    type: object
                    properties:
                      affinity:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      topologySpreadConstraints:
                        type: array
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                  modifyWorkspacePorts:
                    type: object
                    properties:
                      executorPort:
                        type: number
                      nginxPort:
                        type: number
                  setSharedDatasetsRW:
                    type: object
                    properties:
                      setSharedDatasetsRW:
                        type: object
                  mlflowModelVolume:
                    type: object
                    properties:
                      mlflow_secret:
                        type: string
                      mlflow_secret_namespace:
                        type: string
                      mlflow_mount_basepath:
                        type: string
                      mlflow_proxy_image:
                        type: string
                      mlflow_download_script_cm:
                        type: string
                      mlflow_proxy_uri:
                        type: string
                      istio_enabled:
                        type: boolean
                      s3_enabled:
                        type: boolean
                      mlflow_pvc_name:
                        type: string
                    required:
                      - mlflow_secret
                      - mlflow_secret_namespace
                      - mlflow_mount_basepath
                      - mlflow_proxy_image
                      - mlflow_download_script_cm
                      - mlflow_proxy_uri
                  cloudWorkloadIdentity:
                    type: object
                    properties:
                      cloud_type:
                        type: string
                        enum: ["aws", "gcp", "azure"]
                      user_mappings:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      assume_sa_mapping:
                        type: boolean
                        default: false
                      default_sa:
                        type: string
                        default: ""
                    required:
                      - cloud_type
                      - default_sa
                  terminationGracePeriodSeconds:
                    type: object
                    properties:
                      value:
                        type: integer
                    required:
                      - value
                  insertBuildArgs:
                    type: object
                    properties:
                      assumeRole:
                        type: object
                        properties:
                          cred-secret:
                            type: string
                          cred-ns:
                            type: string
                          role-arn:
                            type: string
                          duration-seconds:
                            type: integer
                        required:
                          - cred-secret
                          - cred-ns
                          - role-arn
                          - duration-seconds
                      buildArgs:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                            - name
                            - value
                  jqSelector:
                    type: object
                    required:
                      - query
                    properties:
                      query:
                        type: string
                      args:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          oneOf:
                            - required: [value]
                            - required: [function]
                          properties:
                            name:
                              type: string
                            value:
                              x-kubernetes-preserve-unknown-fields: true
                            function:
                              type: object
                              required:
                                - name
                                - params
                              properties:
                                name:
                                  type: string
                                params:
                                  type: array
                                  items:
                                    type: object
                                    oneOf:
                                      - required: [jq]
                                      - required: [value]
                                    properties:
                                      jq:
                                        type: string
                                      value:
                                        x-kubernetes-preserve-unknown-fields: true

                  addLdapSupplementalGroups:
                    type: string

      subresources:
        status: {}
