apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: validations.apps.dominodatalab.com
spec:
  group: apps.dominodatalab.com
  names:
    kind: Validation
    listKind: ValidationList
    plural: validations
    singular: validation
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - rules
          properties:
            rules:
              type: array
              items:
                type: object
                properties:
                  labelSelectors:
                    type: array
                    items:
                      type: string
                  queryValidation:
                    type: object
                    properties:
                      message:
                        type: string
                        default: "failing because of generic validation"
                  enforceCpuLicenseLimit:
                    type: object
                    properties:
                      image_for_license_enforcement:
                        type: string
                      cpu_limit:
                        type: number
                      message:
                        type: string
                        default: "No of cores in operation exceed license limit"
                    required:
                      - image_for_license_enforcement
                      - cpu_limit
                  jqSelector:
                    type: object
                    required:
                      - query
                    properties:
                      query:
                        type: string
                      args:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          oneOf:
                            - required: [value]
                            - required: [function]
                          properties:
                            name:
                              type: string
                            value:
                              x-kubernetes-preserve-unknown-fields: true
                            function:
                              type: object
                              required:
                                - name
                                - params
                              properties:
                                name:
                                  type: string
                                params:
                                  type: array
                                  items:
                                    type: object
                                    oneOf:
                                      - required: [jq]
                                      - required: [value]
                                    properties:
                                      jq:
                                        type: string
                                      value:
                                        x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
