apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.env.name }}-webhook"
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: {{ .Values.webhook_port }}
      protocol: TCP
    - port: {{ .Values.metrics_port }}
      protocol: TCP
  podSelector:
    matchLabels:
      app: operator-webhook
  policyTypes:
  - Ingress