apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.env.name }}-webhook"
  name: {{ .Values.env.service }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.webhook_port }}
  selector:
    app: "{{ .Values.env.name }}-webhook"
  sessionAffinity: None
  type: ClusterIP