apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "{{ .Values.env.name }}-valiation-webhook"
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Values.env.namespace.platform }}/{{ .Values.env.name }}-webhook-certificate"
webhooks:
  - name: "{{ .Values.env.name }}-webhook.k8s.twr.io"
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: "{{ .Values.env.service }}"
        namespace: "{{ .Values.env.namespace.platform }}"
        path: "/validate"
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: "{{ .Values.env.name }}-enabled"
          operator: Exists
    rules:
      - operations:
          - "CREATE"
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - "pods"
        scope: "Namespaced"
    failurePolicy: "{{ .Values.mutation.failurePolicy }}"
    timeoutSeconds: {{ int .Values.mutation.timeoutSeconds | default 10 }}
