apiVersion: v2
name: domino-triton
version: 2.1.0
appVersion: "2.1.0"
description: Triton Inference Server with Domino authentication proxies (gRPC and REST)
home: https://github.com/domino-field/domino-triton-inference
keywords:
  - triton-inference
  - dominodatalab
  - grpc
  - rest
  - inference
maintainers:
  - email: sameer.wadkar@dominodatalab.com
    name: Sameer Wadkar