image:
  repository: quay.io/domino
  serverContainer: irsa
  memcachedContainer: memcached
  clientContainer: irsa-client
  serverAppVersion: mdoan_PS-10380
  memcachedVersion: 1.6.22
  clientAppVersion: mdoan_PS-10380
  pullPolicy: Always
env:
  name: irsa
  service: irsa-svc
  eks_aws_account: '946429944765'
  assets_aws_account: '946429944765'
  eks_service_role_name: marcdo27843-domino-irsa-svc-role
  oidc_provider: oidc.eks.us-west-2.amazonaws.com/id/C7F107CAE94B194C9AF67A09A84B878B
  oidc_provider_audience: sts.amazonaws.com
  aws_default_region: us-west-2
  aws_region: us-west-2
  aws_sts_regional_endpoints: regional
  govcloud: false
  namespace:
    platform: domino-platform
    compute: domino-compute
    field: domino-field
  memcached:
    max_memory: 1024 # max mem for memcached in MB    
istio:
  enabled: false