{
 "title": "IRSA Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Query ConfigMap to Org Mapping ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(irsa_query_config_map_org_to_iamrole_mapping_total[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(irsa_query_config_map_org_to_iamrole_mapping_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Org Mapping Query Panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(irsa_query_user_org_membership_total[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(irsa_failed_query_user_org_membership_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query User Principal Metrics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(irsa_query_user_principal_total[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(irsa_failed_query_user_principal_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IRSA Call Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(irsa_mapping_requests_total[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(irsa_failed_maping_requests_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}