apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: cloud-workload-identity
  namespace: domino-platform
rules:
# Map to individual users, azure
- labelSelectors:
  - "dominodatalab.com/workload-engine=cg2"
  cloudWorkloadIdentity:
    cloud_type: aws
    default_sa: aws-test
    user_mappings:
      integration-test: aws-test
