apiVersion: v1
kind: Pod
metadata:
  name: s3-test
  namespace: domino-compute
spec:
  serviceAccountName: aws-test
  containers:
  - name: sh
    image: amazonlinux
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: s3
      mountPath: /mnt/s3
  volumes:
  - name: s3
    persistentVolumeClaim:
      claimName: mountpoints3-user-pvc