kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}-extendedapi"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.env.name }}"
  namespace: {{ .Values.env.namespace.field }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.env.name }}"
  apiGroup: rbac.authorization.k8s.io
