kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
rules:
- apiGroups:
  - apps.dominodatalab.com
  resources:
  - "mutations"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
  - "list" 
  - "delete" 
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
  - "list"  