apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.env.name }}"
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 5000
      protocol: TCP
  podSelector:
    matchLabels:
      app: "{{ .Values.env.name }}"
  policyTypes:
  - Ingress