kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.platform }}"
rules:
- apiGroups:
  - apps.dominodatalab.com
  resources:
  - "mutations"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
  - "list" 
  - "delete" 
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
  - "list"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.compute }}"
rules:
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - "get"
  - "create"
  - "update"
  - "patch"
  - "list"
  - "delete"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.system }}"
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
