apiVersion: v1
kind: ConfigMap
metadata:
  name: domino-org-iamrole-mapping
data: {
    "irsa-iamrole-list-bucket":"{\"proxy_iam_role_arn\":\"arn:aws:iam::{{.Values.env.eks_aws_account}}:role/{{.Values.env.role_prefix}}-list-bucket-role\",\"iam_role_arn\":\"arn:aws:iam::{{.Values.env.assets_aws_account}}:role/{{.Values.env.role_prefix}}-list-bucket-role\"}",
    "irsa-iamrole-read-bucket":"{\"proxy_iam_role_arn\":\"arn:aws:iam::{{.Values.env.eks_aws_account}}:role/{{.Values.env.role_prefix}}-read-bucket-role\",\"iam_role_arn\":\"arn:aws:iam::{{.Values.env.assets_aws_account}}:role/{{.Values.env.role_prefix}}-read-bucket-role\"}",
    "irsa-iamrole-update-bucket":"{\"proxy_iam_role_arn\":\"arn:aws:iam::{{.Values.env.eks_aws_account}}:role/{{.Values.env.role_prefix}}-update-bucket-role\",\"iam_role_arn\":\"arn:aws:iam::{{.Values.env.assets_aws_account}}:role/{{.Values.env.role_prefix}}-update-bucket-role\"}"
  }

