name: "yolov8n"
platform: "onnxruntime_onnx"
max_batch_size: 16

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, -1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

# For CPU deployment, replace instance_group with:
# instance_group [
#   {
#     kind: KIND_CPU
#     count: 1
#   }
# ]

version_policy {
  all { }
}

# Dynamic batching - Triton will automatically batch requests
dynamic_batching {
  preferred_batch_size: [ 1, 2, 4, 8 ]
  max_queue_delay_microseconds: 100
}
